# Getting Started with Lucky Parking Los Angeles Citation Data

Here is some code and data to get new data scientists and analysts started. To use this notebook, please ask Lucky Parking leaders to give access to the Lucky Parking Google Drive.

Get started by saving your own version and doing your own analysis. Go to 'File' and select 'Save a copy in Drive'. Make sure you're saving it to your own Google Drive account.

In [1]:
# Allowing Google Colab to access the data stored in the Lucky Parking Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Importing basic data analysis and visualization packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Optional packages for geospatial analysis
# !pip install geopandas
# import geopandas as gpd
# from pyproj import Transformer

Mounted at /content/drive

In [2]:
# Load 20% sampling of raw citation data with Pandas and low_memory=False parameter
df = pd.read_csv(
    '/content/drive/Shareddrives/Lucky Parking Drive/Lucky Parking Folder/Data/2022-07-02_raw.csv', 
    low_memory=False
    )
df.sample(5)

,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,...,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude,Agency Description,Color Description,Body Style Description
340027,03/13/2015,812.0,NaN,NaN,CA,201603.0,NaN,HYUN,PA,GY,...,00356,53.0,80.69BS,NO PARK/STREET CLEAN,73.0,9.999900e+04,9.999900e+04,NaN,NaN,NaN
2423920,01/10/2020,1336.0,NaN,NaN,CA,202011.0,NaN,FORD,PU,GY,...,340R,53.0,80.61,STANDNG IN ALLEY,68.0,6.444756e+06,1.904187e+06,53 - DOT - VALLEY,GREY,PICK-UP TRUCK
460512,06/10/2015,1256.0,NaN,NaN,CA,201512.0,NaN,KIA,PA,SL,...,00441,54.0,80.69BS,NO PARK/STREET CLEAN,73.0,6.473000e+06,1.858045e+06,NaN,NaN,NaN
1028367,02/22/2017,1135.0,SS428,NaN,CA,NaN,NaN,BMW,PA,BL,...,00141,51.0,88.13B+,METER EXP.,63.0,6.426124e+06,1.839184e+06,NaN,NaN,NaN
43497,02/03/2016,1742.0,NaN,NaN,CA,201701.0,NaN,TOYT,PA,SL,...,00309,53.0,80.56E4+,RED ZONE,93.0,9.999900e+04,9.999900e+04,NaN,NaN,NaN