In [2]:
import gmaps


gmaps.configure(api_key='') # Fill in with your API key

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [8]:
df=pd.read_csv("C:\Parking_Citations_After_July_1_2015.csv",low_memory=False)
df.head(10)

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
0,4361370075,2019/09/17 12:00:00 AM,817.0,NaN,NaN,LA,NaN,MERC,PA,RD,1324 84TH PL W,00551,55.0,80.69BS,NO PARK/STREET CLEAN,73,6.471017e+06,1.808559e+06
1,4361370064,2019/09/17 12:00:00 AM,811.0,VM48,NaN,CA,NaN,BUIC,PA,GN,1000 85TH ST W,00551,55.0,88.13B+,METER EXP.,63,6.473192e+06,1.808298e+06
2,4361370053,2019/09/17 12:00:00 AM,809.0,NaN,NaN,CA,NaN,TOYT,PA,GY,1000 85TH ST W,00551,55.0,80.69BS,NO PARK/STREET CLEAN,73,6.473192e+06,1.808298e+06
3,4361370042,2019/09/17 12:00:00 AM,805.0,NaN,NaN,CA,NaN,NISS,PA,BK,8021 VERMONT AVE,00551,55.0,80.69BS,NO PARK/STREET CLEAN,73,6.473164e+06,1.810388e+06
4,4361370031,2019/09/17 12:00:00 AM,727.0,NaN,NaN,CA,NaN,HOND,PA,GY,1473 45TH ST W,00551,55.0,22500E,BLOCKING DRIVEWAY,68,6.469917e+06,1.823537e+06
5,4361370016,2019/09/17 12:00:00 AM,611.0,NaN,NaN,CA,NaN,NISS,PA,BL,1507 FLORENCE AVE,00551,55.0,22500F,PARKED ON SIDEWALK,68,9.999900e+04,9.999900e+04
6,4361354034,2019/09/17 12:00:00 AM,1750.0,MD413,NaN,CA,NaN,HOND,PA,GY,1601 EASTLAKE AV,00600,56.0,88.13B+,METER EXP.,63,6.498692e+06,1.846041e+06
7,4361342101,2019/09/17 12:00:00 AM,1452.0,NaN,NaN,CA,NaN,FORD,PU,WT,530 LOS ANGELES ST S,00665,56.0,80.56E4+,RED ZONE,93,6.486540e+06,1.839072e+06
8,4361342090,2019/09/17 12:00:00 AM,1320.0,CB2607,NaN,CA,NaN,VOLK,PA,BL,402 8TH ST E,00665,56.0,88.13B+,METER EXP.,63,6.484173e+06,1.838669e+06
9,4361342086,2019/09/17 12:00:00 AM,1316.0,NaN,NaN,CA,NaN,MERZ,PA,SL,841 MAPLE AVE S,00665,56.0,80.56E4+,RED ZONE,93,6.485386e+06,1.837137e+06

In [87]:
df["Date"] = df["Issue Date"].apply(lambda x: x.split()[0])

In [125]:
df[df["Agency"] == 55]["Route"].nunique()

172

In [120]:
df["Route"].value_counts().shape

(5274,)

In [117]:
df[df["Issue Date"].str.contains("2019/02/02")].groupby(["Route", "Agency"]).size()

Route  Agency
00101  51.0       1
       53.0      21
       54.0      11
00103  51.0      14
00133  51.0      12
00135  51.0       4
00157  1.0        1
00174  51.0      12
00201  51.0      11
00203  51.0      12
00204  51.0      20
00300  51.0      13
00301  51.0       3
00302  51.0      68
00305  51.0      34
00308  51.0      21
00309  53.0      29
00310  53.0      17
00312  51.0      15
00315  53.0      29
00319  53.0      14
00351  53.0      13
00352  53.0       2
00355  53.0      15
00359  53.0       1
00363  1.0        2
       53.0       6
00371  53.0      14
00372  53.0      15
00373  53.0       3
                 ..
311W   51.0      31
314W   51.0      28
330R2  53.0      10
340R   53.0       7
350A   53.0       6
350R1  53.0       8
360R1  53.0       5
369A   53.0      16
378R1  53.0      16
3A206  2.0        2
3C103  2.0        2
3C151  2.0        1
3C207  2.0        1
3C7B   2.0        1
401A   54.0      13
401B   54.0      68
402A   54.0      75
402B   54.0      25
403B   54.0      14
503A   51.0      16
504A   51.0      22
506A   51.0      39
506C   51.0      11
6A77   1.0        1
6X99   1.0        1
8A53   1.0        5
8A95   1.0        1
9A41   1.0        5
PATRO  1.0        1
W4     1.0        1
Length: 133, dtype: int64

In [88]:
df["Date"] = pd.to_datetime(df["Date"])

In [90]:
df.sort_values(by=["Agency", "Date", "Issue time"])

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,VIN,Make,Body Style,Color,...,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude,Latitude_1,Longitude_1,Date
7565847,1067717700,2016/01/12 12:00:00 AM,150.0,NaN,NaN,CA,NaN,CHEV,TR,BK,...,00667,1.0,8056E4,RED ZONE,93,6.463660e+06,1.858863e+06,34.044502,-118.283292,2016-01-12
7565756,1110476721,2016/01/12 12:00:00 AM,1115.0,NaN,NaN,WA,NaN,HOND,PA,BK,...,01779,1.0,4000A1,NO EVIDENCE OF REG,50,6.418335e+06,1.906609e+06,34.087237,-118.181836,2016-01-12
7565782,1109141854,2016/01/12 12:00:00 AM,1115.0,NaN,NaN,CA,NaN,BMW,NaN,BK,...,35M54,1.0,4000A1,NO EVIDENCE OF REG,50,6.399657e+06,1.912673e+06,34.141436,-118.371126,2016-01-12
7565823,1108722742,2016/01/12 12:00:00 AM,1505.0,NaN,NaN,CA,NaN,FORD,SU,BK,...,MQ,1.0,225078A,HANDICAP/NO DP ID,363,6.475973e+06,1.816265e+06,34.148068,-118.369134,2016-01-12
7565805,1109341251,2016/01/12 12:00:00 AM,1520.0,NaN,NaN,CA,NaN,CHEV,PA,NaN,...,MQ,1.0,225078A,HANDICAP/NO DP ID,363,6.468016e+06,1.818569e+06,34.151028,-118.350629,2016-01-12
7565804,1109341262,2016/01/12 12:00:00 AM,1540.0,NaN,NaN,CA,NaN,LEXU,PA,BK,...,MQ,1.0,225078A,HANDICAP/NO DP ID,363,6.467667e+06,1.818571e+06,34.151028,-118.350629,2016-01-12
7565803,1109341273,2016/01/12 12:00:00 AM,1550.0,NaN,NaN,CA,NaN,TOYO,PA,RE,...,MQ,1.0,225078A,HANDICAP/NO DP ID,363,6.467714e+06,1.818570e+06,34.144836,-118.361440,2016-01-12
7565800,1109341306,2016/01/12 12:00:00 AM,1605.0,NaN,NaN,CA,NaN,TOYO,VN,BL,...,MQ,1.0,570,2251157B,363,6.468016e+06,1.818569e+06,34.172150,-118.387093,2016-01-12
7565801,1109341295,2016/01/12 12:00:00 AM,1605.0,NaN,NaN,CA,NaN,TOYO,VN,BL,...,MQ,1.0,225078A,HANDICAP/NO DP ID,363,6.468016e+06,1.818569e+06,34.144741,-118.361439,2016-01-12
7565738,1107687136,2016/01/12 12:00:00 AM,1630.0,NaN,NaN,PA,NaN,NaN,TR,WH,...,SL10,1.0,8056E1,WHITE ZONE,58,6.473465e+06,1.728692e+06,34.098145,-118.294156,2016-01-12
7565739,1107687125,2016/01/12 12:00:00 AM,1630.0,NaN,NaN,CA,NaN,LONG,TL,WH,...,SL10,1.0,8056E1,WHITE ZONE,58,6.473465e+06,1.728692e+06,34.099703,-118.338676,2016-01-12
7565740,1107687114,2016/01/12 12:00:00 AM,1630.0,NaN,NaN,CA,NaN,NISS,TR,BK,...,SL10,1.0,8056E1,WHITE ZONE,58,6.473465e+06,1.728692e+06,34.059900,-118.338950,2016-01-12
7565741,1107687103,2016/01/12 12:00:00 AM,1630.0,NaN,NaN,CA,NaN,CHEV,TR,YE,...,SLD,1.0,8056E4,RED ZONE,93,6.473465e+06,1.728692e+06,34.120060,-118.350921,2016-01-12
7565798,1109341321,2016/01/12 12:00:00 AM,1630.0,NaN,NaN,CA,NaN,CHRY,PA,BK,...,MQ,1.0,570,2251157B,363,6.468016e+06,1.818569e+06,34.140798,-118.367167,2016-01-12
7565799,1109341310,2016/01/12 12:00:00 AM,1630.0,NaN,NaN,CA,NaN,CHRY,PA,BK,...,MQ,1.0,225078A,HANDICAP/NO DP ID,363,6.468016e+06,1.818569e+06,34.140724,-118.366979,2016-01-12
7565760,1108193726,2016/01/12 12:00:00 AM,1705.0,NaN,NaN,CA,NaN,HOND,PA,GY,...,00001,1.0,8056E4,RED ZONE,93,6.442685e+06,1.814505e+06,34.067065,-118.328780,2016-01-12
7565796,1109341343,2016/01/12 12:00:00 AM,1705.0,NaN,NaN,CA,NaN,DODG,PA,GO,...,MQ,1.0,570,2251157B,363,6.468016e+06,1.818569e+06,34.141038,-118.367779,2016-01-12
7565797,1109341332,2016/01/12 12:00:00 AM,1705.0,NaN,NaN,CA,NaN,DODG,PA,GO,...,MQ,1.0,225078A,HANDICAP/NO DP ID,363,6.468016e+06,1.818569e+06,34.141038,-118.367779,2016-01-12
7565795,1109341354,2016/01/12 12:00:00 AM,1730.0,NaN,NaN,CA,NaN,DODG,PA,GY,...,MQ,1.0,225078A,HANDICAP/NO DP ID,363,6.467714e+06,1.818570e+06,34.141038,-118.367779,2016-01-12
7565794,1109341365,2016/01/12 12:00:00 AM,1820.0,NaN,NaN,CA,NaN,NISS,SU,NaN,...,MQ,1.0,225078A,HANDICAP/NO DP ID,363,6.468016e+06,1.818569e+06,34.141426,-118.368766,2016-01-12
7565793,1109341376,2016/01/12 12:00:00 AM,1900.0,NaN,NaN,CA,NaN,KIA,PA,NaN,...,MQ,1.0,225078A,HANDICAP/NO DP ID,363,6.461810e+06,1.818550e+06,34.140933,-118.367511,2016-01-12
7565767,1112950860,2016/01/12 12:00:00 AM,2150.0,NaN,NaN,CA,NaN,FORD,VN,WH,...,NaN,1.0,8069A,NO STOPPING/STANDING,93,6.481278e+06,1.838322e+06,34.064565,-118.349331,2016-01-12
7556818,1109133782,2016/01/13 12:00:00 AM,1030.0,NaN,NaN,CA,NaN,TOYO,PA,GY,...,M29,1.0,225078A,HANDICAP/NO DP ID,363,6.426005e+06,1.903492e+06,34.059925,-118.252340,2016-01-13
7556816,1109133804,2016/01/13 12:00:00 AM,1110.0,NaN,NaN,CA,NaN,LEXU,PA,WH,...,M29,1.0,225078A,HANDICAP/NO DP ID,363,6.422814e+06,1.924235e+06,34.062380,-118.255338,2016-01-13
7556817,1109133793,2016/01/13 12:00:00 AM,1110.0,NaN,NaN,CA,NaN,LEXU,PA,WH,...,M29,1.0,569,2251157A,363,6.422814e+06,1.924235e+06,34.059925,-118.252340,2016-01-13
7556831,1109809982,2016/01/13 12:00:00 AM,1200.0,NaN,NaN,CA,NaN,TOYO,PA,SI,...,NaN,1.0,4000A1,NO EVIDENCE OF REG,50,6.476115e+06,1.872692e+06,34.161715,-118.378973,2016-01-13
7556716,1112591130,2016/01/13 12:00:00 AM,1300.0,NaN,NaN,CA,NaN,TOYO,PA,GR,...,13Q24,1.0,8058L,PREF PARKING,68,6.487099e+06,1.820587e+06,33.782415,-118.281029,2016-01-13
7556708,1112591211,2016/01/13 12:00:00 AM,1430.0,NaN,NaN,CA,NaN,GMC,VN,GR,...,13Q24,1.0,4000A1,NO EVIDENCE OF REG,50,6.486957e+06,1.820256e+06,33.782415,-118.281029,2016-01-13
7556829,1078684821,2016/01/13 12:00:00 AM,1505.0,NaN,NaN,CA,NaN,AUDI,PA,GY,...,21A5,1.0,4000A1,NO EVIDENCE OF REG,50,6.378461e+06,1.892250e+06,34.081320,-118.300435,2016-01-13
7556828,1078684832,2016/01/13 12:00:00 AM,1510.0,NaN,NaN,CA,NaN,LEXU,PA,GY,...,21A29,1.0,4000A1,NO EVIDENCE OF REG,50,6.378461e+06,1.892250e+06,34.075569,-118.300404,2016-01-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14983,4360269863,2019/09/07 12:00:00 AM,1431.0,NaN,NaN,CA,NaN,TOYT,PA,GN,...,58B,58.0,80.69AA+,NO STOP/STAND,93,6.476495e+06,1.828986e+06,34.036926,-118.255300,2019-09-07
14984,4360269874,2019/09/07 12:00:00 AM,1433.0,NaN,NaN,CA,NaN,NISS,PA,WT,...,58B,58.0,80.69AA+,NO STOP/STAND,93,6.476495e+06,1.828986e+06,34.036656,-118.260563,2019-09-07
14985,4360269885,2019/09/07 12:00:00 AM,1450.0,NaN,NaN,WA,NaN,VOLK,PA,SL,...,58B,58.0,80.69AA+,NO STOP/STAND,93,6.476495e+06,1.828986e+06,34.056494,-118.244487,2019-09-07
14986,4360269896,2019/09/07 12:00:00 AM,1510.0,NaN,NaN,CA,NaN,SUBA,PA,BK,...,58B,58.0,80.69AA+,NO STOP/STAND,93,6.476326e+06,1.828730e+06,34.053091,-118.247754,2019-09-07
14990,4360269933,2019/09/07 12:00:00 AM,1702.0,NaN,NaN,CA,NaN,MAZD,PA,GY,...,58B,58.0,80.69AA+,NO STOP/STAND,93,6.476495e+06,1.828986e+06,34.046567,-118.268374,2019-09-07
14991,4360269944,2019/09/07 12:00:00 AM,1704.0,NaN,NaN,CA,NaN,NISS,PA,BK,...,58B,58.0,80.69AA+,NO STOP/STAND,93,6.476495e+06,1.828986e+06,34.046580,-118.268404,2019-09-07
14992,4360269955,2019/09/07 12:00:00 AM,1707.0,NaN,NaN,CA,NaN,NISS,PA,RD,...,58B,58.0,80.69AA+,NO STOP/STAND,93,6.476495e+06,1.828986e+06,34.050907,-118.264299,2019-09-07
14995,4360269981,2019/09/07 12:00:00 AM,1941.0,NaN,NaN,CA,NaN,TOYT,PA,GY,...,58B,58.0,80.69AA+,NO STOP/STAND,93,6.476326e+06,1.828730e+06,34.047144,-118.264949,2019-09-07
5803591,1110880750,2016/10/30 12:00:00 AM,213.0,NaN,NaN,CA,NaN,PONT,PA,BL,...,NaN,59.0,8069A,NO STOPPING/STANDING,93,6.476902e+06,1.830615e+06,34.034631,-118.250497,2016-10-30
5803590,1110880761,2016/10/30 12:00:00 AM,233.0,NaN,NaN,CA,NaN,BMW,PA,WH,...,NaN,59.0,8069A,NO STOPPING/STANDING,93,6.476904e+06,1.830620e+06,34.045163,-118.256865,2016-10-30
5803588,1110880783,2016/10/30 12:00:00 AM,250.0,NaN,NaN,CA,NaN,FORD,TR,GO,...,NaN,59.0,8069A,NO STOPPING/STANDING,93,6.476902e+06,1.830615e+06,34.051190,-118.248367,2016-10-30
5803587,1110880794,2016/10/30 12:00:00 AM,310.0,NaN,NaN,CA,NaN,SUBA,PA,WH,...,NaN,59.0,8069A,NO STOPPING/STANDING,93,6.476641e+06,1.830128e+06,34.045595,-118.245168,2016-10-30
5803586,1110880805,2016/10/30 12:00:00 AM,337.0,NaN,NaN,CA,NaN,TOYO,PA,GY,...,NaN,59.0,8069A,NO STOPPING/STANDING,93,6.476317e+06,1.829521e+06,34.034362,-118.254347,2016-10-30
5803585,1110880816,2016/10/30 12:00:00 AM,350.0,NaN,NaN,CA,NaN,HYUN,PA,GY,...,NaN,59.0,8069A,NO STOPPING/STANDING,93,6.476902e+06,1.830615e+06,34.035004,-118.255341,2016-10-30
5803584,1110880820,2016/10/30 12:00:00 AM,415.0,NaN,NaN,OR,NaN,ACUR,PA,BK,...,NaN,59.0,8069A,NO STOPPING/STANDING,93,6.479644e+06,1.835747e+06,34.045974,-118.271258,2016-10-30
5803583,1110880831,2016/10/30 12:00:00 AM,425.0,NaN,NaN,CA,NaN,MINI,PA,GY,...,NaN,59.0,8069A,NO STOPPING/STANDING,93,6.480013e+06,1.836436e+06,34.110744,-118.190444,2016-10-30
5803582,1110880853,2016/10/30 12:00:00 AM,435.0,NaN,NaN,CA,NaN,HOND,PA,SI,...,NaN,59.0,8069A,NO STOPPING/STANDING,93,6.480013e+06,1.836436e+06,34.121410,-118.206536,2016-10-30
5803581,1110880864,2016/10/30 12:00:00 AM,448.0,NaN,NaN,CA,NaN,TOYO,PA,BK,...,NaN,59.0,8069A,NO STOPPING/STANDING,93,6.480471e+06,1.837285e+06,34.108991,-118.194249,2016-10-30
5803580,1110880875,2016/10/30 12:00:00 AM,457.0,NaN,NaN,CA,NaN,CHEV,PA,BK,...,NaN,59.0,8069A,NO STOPPING/STANDING,93,6.480471e+06,1.837285e+06,34.108988,-118.193943,2016-10-30
5803579,1110880886,2016/10/30 12:00:00 AM,520.0,NaN,NaN,CA,NaN,VOLK,PA,SI,...,NaN,59.0,000,NaN,NaN,6.482061e+06,1.838638e+06,34.108988,-118.193943,2016-10-30
3964299,1111485255,2017/08/19 12:00:00 AM,815.0,NaN,NaN,CA,NaN,BUIC,PA,GY,...,NaN,59.0,8069A,NO STOPPING/STANDING,93,6.409111e+06,1.841813e+06,34.048552,-118.454086,2017-08-19
3690436,1112967800,2017/10/04 12:00:00 AM,1010.0,NaN,NaN,CA,NaN,VW,PA,BK,...,NaN,59.0,80714,PRIVATE PROPERTY,68,6.457487e+06,1.851534e+06,34.020822,-118.200819,2017-10-04
7004355,1111199014,2016/04/13 12:00:00 AM,115.0,389,NaN,CA,NaN,HOND,4D,SI,...,00007,77.0,2251156B,MISUSE/DP PRIVILEGE,363,6.492534e+06,1.833227e+06,34.099029,-118.305627,2016-04-13
6699663,1109566150,2016/06/01 12:00:00 AM,935.0,NaN,NaN,CA,NaN,FORD,PA,BK,...,HARBO,97.0,011,22500F,68,6.479735e+06,1.745626e+06,34.083532,-118.348653,2016-06-01
4531617,1108164680,2017/05/22 12:00:00 AM,1300.0,NaN,NaN,CA,NaN,NISS,SU,RE,...,LA,97.0,80713,PARKING/FRONT YARD 1,68,6.470340e+06,1.853018e+06,34.001706,-118.470903,2017-05-22
6066606,1109182756,2016/09/17 12:00:00 AM,2238.0,NaN,NaN,CA,NaN,HOND,PA,GY,...,NaN,NaN,8603,PK IN PROH AREA,68,6.470141e+06,1.867430e+06,34.098544,-118.347865,2016-09-17
4004377,1117041052,2017/08/13 12:00:00 AM,1750.0,NaN,NaN,NV,NaN,CHEV,PA,SI,...,NaN,NaN,8603,PK IN PROH AREA,68,6.470141e+06,1.867430e+06,34.080296,-118.312509,2017-08-13
2444700,1114562503,2018/04/29 12:00:00 AM,520.0,NaN,NaN,NV,NaN,DODG,PA,BK,...,NaN,NaN,8603,PK IN PROH AREA,68,6.470141e+06,1.867430e+06,34.099816,-118.350172,2018-04-29
1454589,1122387781,2018/11/02 12:00:00 AM,2016.0,NaN,NaN,CA,NaN,MAZD,PA,BK,...,NaN,NaN,8803A,PK OUTSD SPACE,58,6.470141e+06,1.867430e+06,34.049682,-118.270585,2018-11-02
1077134,1124366725,2019/01/21 12:00:00 AM,2300.0,NaN,NaN,CA,NaN,CHEV,PA,GY,...,NaN,NaN,6344K2,NO PK BET 1-3AM,68,6.454397e+06,1.850279e+06,34.027301,-118.302761,2019-01-21

In [5]:
df["Agency"].nunique()

5

In [12]:
df.shape

(8706412, 18)

In [9]:
df[["Ticket number"]].min()

Ticket number    1.001096e+09
dtype: float64

In [11]:
df[["Ticket number"]].max()

Ticket number    4.361460e+09
dtype: float64

In [29]:
df=df[df['Latitude']!=99999]
df=df[df['Longitude']!=99999]
print(df['Latitude'].min(), df['Latitude'].max())
print(df['Longitude'].min(), df['Longitude'].max())
df.head()

6359739.30402891 6514332.07372465
1715555.176091 1942668.996228

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude,Latitude_1,Longitude_1
0,4361370075,2019/09/17 12:00:00 AM,817.0,NaN,NaN,LA,NaN,MERC,PA,RD,1324 84TH PL W,00551,55.0,80.69BS,NO PARK/STREET CLEAN,73,6.471017e+06,1.808559e+06,33.961646,-118.298938
1,4361370064,2019/09/17 12:00:00 AM,811.0,VM48,NaN,CA,NaN,BUIC,PA,GN,1000 85TH ST W,00551,55.0,88.13B+,METER EXP.,63,6.473192e+06,1.808298e+06,33.960946,-118.291763
2,4361370053,2019/09/17 12:00:00 AM,809.0,NaN,NaN,CA,NaN,TOYT,PA,GY,1000 85TH ST W,00551,55.0,80.69BS,NO PARK/STREET CLEAN,73,6.473192e+06,1.808298e+06,33.960946,-118.291763
3,4361370042,2019/09/17 12:00:00 AM,805.0,NaN,NaN,CA,NaN,NISS,PA,BK,8021 VERMONT AVE,00551,55.0,80.69BS,NO PARK/STREET CLEAN,73,6.473164e+06,1.810388e+06,33.966689,-118.291875
4,4361370031,2019/09/17 12:00:00 AM,727.0,NaN,NaN,CA,NaN,HOND,PA,GY,1473 45TH ST W,00551,55.0,22500E,BLOCKING DRIVEWAY,68,6.469917e+06,1.823537e+06,34.002795,-118.302713

In [23]:
import pyproj
from pyproj import Proj, transform

In [24]:

x, y = df["Latitude"].tolist(), df["Longitude"].tolist()
inProj = Proj(init='epsg:2229', preserve_units=True) # make sure unit preserve 
outProj = Proj(init='epsg:4326')
y_1,x_1 = transform(inProj,outProj,x,y)
df["Latitude_1"] = pd.Series(x_1)

df["Longitude_1"] = pd.Series(y_1)
print(x_1, y_1)
df.head(2)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude,Latitude_1,Longitude_1
0,4361370075,2019/09/17 12:00:00 AM,817.0,NaN,NaN,LA,NaN,MERC,PA,RD,1324 84TH PL W,00551,55.0,80.69BS,NO PARK/STREET CLEAN,73,6.471017e+06,1.808559e+06,33.961646,-118.298938
1,4361370064,2019/09/17 12:00:00 AM,811.0,VM48,NaN,CA,NaN,BUIC,PA,GN,1000 85TH ST W,00551,55.0,88.13B+,METER EXP.,63,6.473192e+06,1.808298e+06,33.960946,-118.291763

In [32]:
skip = pd.Series(np.random.binomial(1, 0.1, len(df)), index=df.index)

In [33]:
subset = df[skip==1]

In [34]:
df.shape, subset.shape

((6782765, 20), (678810, 20))

In [38]:
#subset["Issue Date"] = pd.to_datetime(subset["Issue Date"], infer_datetime_format=True)

In [47]:
df.isnull().mean()

Ticket number            0.000000e+00
Issue Date               0.000000e+00
Issue time               1.683679e-04
Meter Id                 7.339026e-01
Marked Time              9.662430e-01
RP State Plate           1.385865e-05
VIN                      1.000000e+00
Make                     5.242700e-04
Body Style               5.014179e-04
Color                    1.820791e-04
Location                 0.000000e+00
Route                    4.240159e-03
Agency                   7.371625e-07
Violation code           0.000000e+00
Violation Description    4.349259e-05
Fine amount              2.580069e-04
Latitude                 0.000000e+00
Longitude                0.000000e+00
Latitude_1               0.000000e+00
Longitude_1              0.000000e+00
dtype: float64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7570561 entries, 0 to 8706411
Data columns (total 20 columns):
Ticket number            object
Issue Date               object
Issue time               float64
Meter Id                 object
Marked Time              float64
RP State Plate           object
VIN                      float64
Make                     object
Body Style               object
Color                    object
Location                 object
Route                    object
Agency                   float64
Violation code           object
Violation Description    object
Fine amount              object
Latitude                 float64
Longitude                float64
Latitude_1               float64
Longitude_1              float64
dtypes: float64(8), object(12)
memory usage: 1.2+ GB

In [30]:
df=df[~df['Latitude_1'].isnull()]
df=df[~df['Latitude'].isnull()]
df.isnull().sum()

Ticket number                  0
Issue Date                     0
Issue time                  1142
Meter Id                 4977889
Marked Time              6553799
RP State Plate                94
VIN                      6782765
Make                        3556
Body Style                  3401
Color                       1235
Location                       0
Route                      28760
Agency                         5
Violation code                 0
Violation Description        295
Fine amount                 1750
Latitude                       0
Longitude                      0
Latitude_1                     0
Longitude_1                    0
dtype: int64

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6782765 entries, 0 to 7570560
Data columns (total 20 columns):
Ticket number            object
Issue Date               object
Issue time               float64
Meter Id                 object
Marked Time              float64
RP State Plate           object
VIN                      float64
Make                     object
Body Style               object
Color                    object
Location                 object
Route                    object
Agency                   float64
Violation code           object
Violation Description    object
Fine amount              object
Latitude                 float64
Longitude                float64
Latitude_1               float64
Longitude_1              float64
dtypes: float64(8), object(12)
memory usage: 1.1+ GB

In [32]:
gmaps.configure(api_key='')
rdf = df[df["Violation Description"] == "RED ZONE"]
locations = rdf.iloc[:100000][["Latitude_1","Longitude_1"]]
fig = gmaps.figure()
fig.add_layer(gmaps.heatmap_layer(locations))
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
'''gmaps.configure(api_key='')
issue_time_morning = (df["Issue time"] > 800) & (df["Issue time"] < 1200)
few_data = df[issue_time_morning][df["Violation Description"] == "RED ZONE"]
locations = few_data.iloc[:10000][["Latitude_1","Longitude_1"]]
fig = gmaps.figure()
layer = gmaps.symbol_layer(locations, fill_color = "red", stroke_color = "red", scale = 1)
fig.add_layer(layer)
fig'''

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

Figure(layout=FigureLayout(height='420px'))

In [17]:
#picked 100000 samples since my computer cannot process more data than that 
gmaps.configure(api_key='')
morning_time = (df["Issue time"] > 600) & (df["Issue time"] <= 1200) & (df.iloc[:100000]["Violation Description"] == "RED ZONE")
morning_time_df = df[morning_time][["Latitude_1","Longitude_1"]]

afternoon_time = (df["Issue time"] > 1200) & (df["Issue time"] <= 1800) & (df.iloc[:100000]["Violation Description"] == "RED ZONE")
afternoon_time_df = df[afternoon_time][["Latitude_1","Longitude_1"]]

evening_time = (df["Issue time"] > 1800)  & (df.iloc[:100000]["Violation Description"] == "RED ZONE")
evening_time_df = df[evening_time][["Latitude_1","Longitude_1"]]

fig = gmaps.figure()
morning_layer = gmaps.symbol_layer(morning_time_df, fill_color = "red", stroke_color = "red", scale = 1)
afternoon_layer = gmaps.symbol_layer(afternoon_time_df, fill_color = "green", stroke_color = "green", scale = 1)
evening_layer = gmaps.symbol_layer(evening_time_df, fill_color = "blue", stroke_color = "blue", scale = 1)
fig.add_layer(morning_layer)
fig.add_layer(afternoon_layer)
fig.add_layer(evening_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [112]:
jan_2019_df = df[df["Issue Date"].str.contains("2019/02/02")]
route = jan_2019_df[(jan_2019_df["Route"] == "00101") & (jan_2019_df["Agency"] == 54)]

In [113]:
route["Issue Date"].unique()

array(['2019/02/02 12:00:00 AM'], dtype=object)

In [114]:
#route["Issue Date"].unique()

In [115]:
route["Agency"].unique()

array([54.])

In [85]:
r_df = route[route["Violation Description"] == "RED ZONE"]
r_df.head()

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude,Latitude_1,Longitude_1
998739,4346059734,2019/02/03 12:00:00 AM,1055.0,NaN,NaN,CA,NaN,FORD,PA,RD,700 BERENDO ST,00405,54.0,80.56E4+,RED ZONE,93,6.472576e+06,1.844260e+06,34.046905,-118.238080
998741,4346059712,2019/02/03 12:00:00 AM,931.0,NaN,NaN,CA,NaN,HOND,PA,WT,2800 JAMES M WOOD BLVD,00405,54.0,80.56E4+,RED ZONE,93,6.474106e+06,1.842852e+06,34.048446,-118.247702
998742,4346059701,2019/02/03 12:00:00 AM,929.0,NaN,NaN,CA,NaN,NISS,PA,SL,852 VERMONT AVE S,00405,54.0,80.56E4+,RED ZONE,93,6.473335e+06,1.843167e+06,34.049560,-118.245853
998743,4346059690,2019/02/03 12:00:00 AM,927.0,NaN,NaN,CA,NaN,VOLK,PA,WT,852 VERMONT AVE S,00405,54.0,80.56E4+,RED ZONE,93,6.473335e+06,1.843167e+06,34.050116,-118.276264
998744,4346059686,2019/02/03 12:00:00 AM,926.0,NaN,NaN,CA,NaN,HOND,PA,GY,852 VERMONT AVE S,00405,54.0,80.56E4+,RED ZONE,93,6.473335e+06,1.843167e+06,34.050116,-118.276264

In [116]:
gmaps.configure(api_key='')

morning_time = (r_df["Issue time"] > 0) & (r_df["Issue time"] <= 800)
locations = route[["Latitude_1","Longitude_1"]]


fig = gmaps.figure()
fig.add_layer(gmaps.heatmap_layer(locations))
fig

Figure(layout=FigureLayout(height='420px'))

In [63]:
locations

Empty DataFrame
Columns: [Latitude_1, Longitude_1]
Index: []

In [ ]:
jan_2019_df.head()

In [11]:
gmaps.configure(api_key='')
r_df = df[df["Violation Description"] == "RED ZONE"]
t0 = r_df["Issue time"] <= 600
t1 = (r_df["Issue time"] > 600) & (r_df["Issue time"] <= 700)
t2 = (r_df["Issue time"] > 1200) & (r_df["Issue time"] <= 1300)
t3 = (r_df["Issue time"] > 1800) & (r_df["Issue time"] <= 1900)
locations0 = r_df[t0][["Latitude_1","Longitude_1"]]
locations1 = r_df[t1][["Latitude_1","Longitude_1"]]
locations2 = r_df[t2][["Latitude_1","Longitude_1"]]
locations3 = r_df[t3][["Latitude_1","Longitude_1"]]

In [12]:
fig0 = gmaps.figure()
fig0.add_layer(gmaps.heatmap_layer(locations0))
fig0

Figure(layout=FigureLayout(height='420px'))

In [22]:
fig1 = gmaps.figure()
fig1.add_layer(gmaps.heatmap_layer(locations1))
fig1

Figure(layout=FigureLayout(height='420px'))

In [23]:
fig2 = gmaps.figure()
fig2.add_layer(gmaps.heatmap_layer(locations2))
fig2

Figure(layout=FigureLayout(height='420px'))

In [24]:
fig3 = gmaps.figure()
fig3.add_layer(gmaps.heatmap_layer(locations3))
fig3

Figure(layout=FigureLayout(height='420px'))